In [51]:
import pandas as pd

In [52]:
df_sismos=pd.read_csv("SSNMX_catalogo_20000101_20051231.csv",skiprows=4,skipfooter=7,engine="python")
df_sismos.head()

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,2000-01-01,00:55:51,3.5,17.12,-100.57,29.0,"13 km al SURESTE de TECPAN, GRO",2000-01-01,06:55:51,revisado
1,2000-01-02,11:35:17,4.3,16.07,-97.35,16.0,"11 km al NORESTE de RIO GRANDE, OAX",2000-01-02,17:35:17,revisado
2,2000-01-02,22:32:36,3.9,16.01,-98.62,6.0,"71 km al SUROESTE de PINOTEPA NACIONAL, OAX",2000-01-03,04:32:36,revisado
3,2000-01-03,01:55:15,3.4,17.74,-96.88,83.0,"53 km al SURESTE de TEPELMEME, OAX",2000-01-03,07:55:15,revisado
4,2000-01-03,04:08:44,3.5,18.30,-94.91,15.0,"25 km al SURESTE de CATEMACO, VER",2000-01-03,10:08:44,revisado

In [53]:
df_sismos["Magnitud"]=pd.to_numeric(df_sismos["Magnitud"], errors="coerce")
df_sismos

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,2000-01-01,00:55:51,3.5,17.12,-100.57,29.0,"13 km al SURESTE de TECPAN, GRO",2000-01-01,06:55:51,revisado
1,2000-01-02,11:35:17,4.3,16.07,-97.35,16.0,"11 km al NORESTE de RIO GRANDE, OAX",2000-01-02,17:35:17,revisado
2,2000-01-02,22:32:36,3.9,16.01,-98.62,6.0,"71 km al SUROESTE de PINOTEPA NACIONAL, OAX",2000-01-03,04:32:36,revisado
3,2000-01-03,01:55:15,3.4,17.74,-96.88,83.0,"53 km al SURESTE de TEPELMEME, OAX",2000-01-03,07:55:15,revisado
4,2000-01-03,04:08:44,3.5,18.30,-94.91,15.0,"25 km al SURESTE de CATEMACO, VER",2000-01-03,10:08:44,revisado
...,...,...,...,...,...,...,...,...,...,...
7958,2005-12-30,06:19:12,4.0,16.03,-98.31,6.0,"44 km al SUROESTE de PINOTEPA NACIONAL, OAX",2005-12-30,12:19:12,revisado
7959,2005-12-30,11:24:00,4.4,16.19,-93.85,55.0,"7 km al SURESTE de ARRIAGA , CHIS",2005-12-30,17:24:00,revisado
7960,2005-12-30,18:35:41,4.3,15.77,-93.51,92.0,"34 km al NOROESTE de PIJIJIAPAN, CHIS",2005-12-31,00:35:41,revisado
7961,2005-12-30,22:34:47,4.2,15.69,-94.80,20.0,"69 km al SURESTE de SALINA CRUZ, OAX",2005-12-31,04:34:47,revisado
7962,2005-12-31,18:03:17,4.0,16.00,-97.61,16.0,"19 km al OESTE de RIO GRANDE, OAX",2006-01-01,00:03:17,revisado

In [54]:
df_sismos["Magnitud"].isnull().sum()

np.int64(18)

In [55]:
df_sismos[df_sismos["Magnitud"].isnull()]

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
76,2000-02-03,12:29:45,NaN,28.12,-111.43,10.0,"57 km al NOROESTE de H GUAYMAS, SON",2000-02-03,18:29:45,revisado
107,2000-02-14,20:01:18,NaN,27.95,-111.64,10.0,"73 km al OESTE de H GUAYMAS, SON",2000-02-15,02:01:18,revisado
108,2000-02-14,21:10:22,NaN,27.96,-111.68,10.0,"77 km al OESTE de H GUAYMAS, SON",2000-02-15,03:10:22,revisado
179,2000-03-05,04:50:36,NaN,27.86,-111.80,10.0,"74 km al NORESTE de SANTA ROSALIA, BCS",2000-03-05,10:50:36,revisado
281,2000-04-04,20:15:29,NaN,28.62,-113.03,10.0,"124 km al NORESTE de GUERRERO NEGRO, BCS",2000-04-05,01:15:29,revisado
289,2000-04-09,09:07:28,NaN,28.04,-113.10,10.0,"94 km al ESTE de GUERRERO NEGRO, BCS",2000-04-09,14:07:28,revisado
309,2000-04-14,10:32:56,NaN,27.56,-111.54,10.0,"75 km al SUROESTE de H GUAYMAS, SON",2000-04-14,15:32:56,revisado
1042,2000-12-27,11:58:20,NaN,29.99,-113.54,10.0,"147 km al SUR de PUERTO PEÑASCO, SON",2000-12-27,17:58:20,revisado
1045,2000-12-29,00:14:35,NaN,29.43,-113.73,10.0,"166 km al NORTE de GUERRERO NEGRO, BCS",2000-12-29,06:14:35,revisado
1084,2001-01-16,00:28:47,NaN,30.57,-113.55,10.0,"83 km al SUR de PUERTO PEÑASCO, SON",2001-01-16,06:28:47,revisado
1085,2001-01-16,01:00:37,NaN,30.59,-113.58,10.0,"81 km al SUR de PUERTO PEÑASCO, SON",2001-01-16,07:00:37,revisado
1088,2001-01-16,09:06:29,NaN,30.46,-113.55,10.0,"95 km al SUR de PUERTO PEÑASCO, SON",2001-01-16,15:06:29,revisado
1106,2001-01-22,03:58:42,NaN,28.02,-111.79,10.0,"88 km al OESTE de H GUAYMAS, SON",2001-01-22,09:58:42,revisado
1150,2001-02-18,12:55:24,NaN,29.15,-113.21,10.0,"156 km al NORESTE de GUERRERO NEGRO, BCS",2001-02-18,18:55:24,revisado
1208,2001-03-15,12:17:58,NaN,28.13,-111.95,10.0,"91 km al SUROESTE de M ALEMAN(LA DOCE), SON",2001-03-15,18:17:58,revisado
1231,2001-04-04,14:39:50,NaN,26.14,-109.66,10.0,"55 km al NOROESTE de AHOME, SIN",2001-04-04,20:39:50,revisado
1469,2001-07-04,11:23:50,NaN,28.74,-111.04,10.0,"41 km al SUR de HERMOSILLO, SON",2001-07-04,16:23:50,revisado
1525,2001-07-24,00:39:57,NaN,26.04,-110.43,10.0,"91 km al ESTE de LORETO, BCS",2001-07-24,05:39:57,revisado

In [56]:
number_nas=df_sismos["Magnitud"].isnull().sum() 
percentage_NA=df_sismos[df_sismos["Magnitud"].isnull()]

In [57]:
percentage=number_nas*100/len(df_sismos)
percentage

np.float64(0.22604546025367322)

In [58]:
df_sismos["Magnitud"]= df_sismos["Magnitud"].fillna(df_sismos["Magnitud"].mean())
df_sismos

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,2000-01-01,00:55:51,3.5,17.12,-100.57,29.0,"13 km al SURESTE de TECPAN, GRO",2000-01-01,06:55:51,revisado
1,2000-01-02,11:35:17,4.3,16.07,-97.35,16.0,"11 km al NORESTE de RIO GRANDE, OAX",2000-01-02,17:35:17,revisado
2,2000-01-02,22:32:36,3.9,16.01,-98.62,6.0,"71 km al SUROESTE de PINOTEPA NACIONAL, OAX",2000-01-03,04:32:36,revisado
3,2000-01-03,01:55:15,3.4,17.74,-96.88,83.0,"53 km al SURESTE de TEPELMEME, OAX",2000-01-03,07:55:15,revisado
4,2000-01-03,04:08:44,3.5,18.30,-94.91,15.0,"25 km al SURESTE de CATEMACO, VER",2000-01-03,10:08:44,revisado
...,...,...,...,...,...,...,...,...,...,...
7958,2005-12-30,06:19:12,4.0,16.03,-98.31,6.0,"44 km al SUROESTE de PINOTEPA NACIONAL, OAX",2005-12-30,12:19:12,revisado
7959,2005-12-30,11:24:00,4.4,16.19,-93.85,55.0,"7 km al SURESTE de ARRIAGA , CHIS",2005-12-30,17:24:00,revisado
7960,2005-12-30,18:35:41,4.3,15.77,-93.51,92.0,"34 km al NOROESTE de PIJIJIAPAN, CHIS",2005-12-31,00:35:41,revisado
7961,2005-12-30,22:34:47,4.2,15.69,-94.80,20.0,"69 km al SURESTE de SALINA CRUZ, OAX",2005-12-31,04:34:47,revisado
7962,2005-12-31,18:03:17,4.0,16.00,-97.61,16.0,"19 km al OESTE de RIO GRANDE, OAX",2006-01-01,00:03:17,revisado

In [62]:
df_sismos["Magnitud"].isnull().sum()

np.int64(0)

In [63]:
df_sismos[df_sismos["Magnitud"].isnull()]

Empty DataFrame
Columns: [Fecha, Hora, Magnitud, Latitud, Longitud, Profundidad, Referencia de localizacion, Fecha UTC, Hora UTC, Estatus]
Index: []